baas:
  chainmaker:
    image:
      ca: "chainmakerofficial/chainmaker-ca:v1.3.0"
      consensus: "chainmakerofficial/chainmaker:v2.3.1"
      common: "chainmakerofficial/chainmaker:v2.3.1"
      vm: "chainmakerofficial/chainmaker-vm-engine:v2.3.1"
      db: ""
    k8s:
      namespace: chainmaker
