baas:
  fabric:
    image:
      ca: "hyperledger/fabric-ca:1.5.0"
      peer: "hyperledger/fabric-peer:2.4.7"
      orderer: "hyperledger/fabric-orderer:2.4.7"
      tools: "hyperledger/fabric-tools:2.4.7"
      db: ""
    k8s:
      namespace: fabric
