baas:
  chainmaker:
    image:
      ca: "chainmakerofficial/chainmaker-ca:v1.3.0"
      consensus: "chainmakerofficial/chainmaker:v2.3.1"
      common: "chainmakerofficial/chainmaker:v2.3.1"
      vm: "chainmakerofficial/chainmaker-vm-engine:v2.3.1"
    blockdb:
      type: "leveldb"
      disable-block-file-db: true
    cadb:
      ip: "127.0.0.1"
      port: "3306"
      username: "root"
      password: "123456aA"
      name: "cadb"
    k8s:
      namespace: chainmaker