baas:
  fabric:
    image:
      ca: "hyperledger/fabric-ca:1.5.0"
      peer: "hyperledger/fabric-peer:2.4.7"
      orderer: "hyperledger/fabric-orderer:2.4.7"
      tools: "hyperledger/fabric-tools:2.4.7"
    dataSource:
      type: "mysql"
      url: "username:passwd@tcp(127.0.0.1:3306)/fabric_ca_db?parseTime=true"
    k8s:
      namespace: fabric
