server:
  address: 0.0.0.0
  port: 8081
  servlet:
    context-path: /
    encoding:
      enabled: true
      force: true
      force-response: true
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8

# profile
spring:
  profiles:
    active: db,dynamictp,fabric,chainmaker
  application:
    name: baas
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

security:
  csrf:
    excludes: ""
    allows: ""

logging:
  config:
    classpath: logback-spring.xml
  level:
    root: info
